### ISSUE TITLE
Work terrible with mixed ore

### ISSUE THREAD

**Issue by Stargateur** [devdot/dqol-resource-monitor#2] opened 2024-08-10 21:19 UTC
I use some mod like https://mods.factorio.com/mod/FunkedOre that do mixed ore, the auto scan work terrible for this use case. It could be nice to support better mixed ore, thus that maybe not a goal of this mod.

**Comment by devdot** [comment] 2024-08-14 07:24
Hi @Stargateur , that mod is interesting. I guess the issue is that I've implemented a site scan that assumes continuous shapes for tile-based resources and that assumption is not true when using the FunkedOre mod. I'll treat all resources as non-continuous resources (like oil) when this mod is active.

This issue will be resolved in 1.1.2

**Closed as completed by devdot** 2024-08-14 07:24 UTC

**Comment by devdot** [comment] 2024-08-14 07:30
Note: The mixed patches will still show up as multiple sites (one for each resource type). Merging multiple resources into one site is beyond the scope of this mod at this point.
